spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - redis
      - actuator
      - docs
  application:
    name: walwal

logging:
  level:
    com.depromeet.walwal.*.api.*: debug
